logging:
  level: INFO
server:
  requestLog:
    appenders: []
special-offers:
  endpoint: "http://192.168.2.2:8080/special-offers"
  connectTimeout: 0
  readTimeout: 0
hystrix:
  executionIsolationThreadTimeoutInMillis: 3000
  executionIsolationStrategy: THREAD
  threadpool:
      threadPoolCoreSize: 10
      keepAliveTimeMinutes: 1
      maxQueueSize: -1
      queueSizeRejectionThreshold: 5
      metricsRollingStatisticalWindowInMilliseconds: 10000
      metricsRollingStatisticalWindowBuckets: 10
  circuitBreaker:
      requestVolumeThreshold: 20
      errorThresholdPercentage: 50
      sleepWindowInMillis: 5000
      metricsRollingStatisticalWindowInMilliseconds: 10000
      metricsRollingStatisticalWindowBuckets: 10
  semaphore:
      maxConcurrentRequests: 10
      fallbackMaxConcurrentRequests: 10
breakerbox:
  urls: http://192.168.2.3:8080/archaius/production
  initialDelay: 10s
  delay: 60s